name: SonarQube Scan

on:
  push:
    branches:
      - main

jobs:
  sonar:
    name: Run SonarQube analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Cache SonarQube scanner
        uses: actions/cache@v2
        with:
          path: ~/.sonar
          key: ${{ runner.os }}-sonar-scanner-cli-6.2.1.4610-Windows-X64
          restore-keys: |
            ${{ runner.os }}-sonar-scanner-cli

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v4
        with:
          sonar-project-key: testero
          sonar-host-url: http://localhost:9000
          sonar-login: sqp_46e069ad57b96d28ca7b11ec9b39ce31feab2cab
        env:
  SONAR_SCANNER_OPTS: "-X"
